% Garrett Scholtes 
% 2017-01-29
% 
% Re-order song data in the order the songs appear
% in our raw postivitity/intensity score spreadsheets

data = csvread('4194304.csv');
% Hard coded (taken from the file "orders", generated by "find_order.py")
order = [7 45 77 12 72 33 25 43 8 49 19 66 9 37 61 68 58 55 60 50 20 2 28 57 29 64 4 14 13 34 6 80 46 69 18 79 62 75 15 67 38 17 76 70 41 10 78 23 56 5 21 26 31 54 32 52 59 3 74 44 53 40 16 39 71 73 48 36 11 35 42 24 65 1 47 22 27 63 51 30];
ordered_data = data(order, :);
csvwrite('4194304_ordered.csv', ordered_data);